# Generated by Django 2.2 on 2021-04-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('user_lvl', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField(max_length=80)),
                ('price', models.IntegerField(default=0)),
                ('completed', models.BooleanField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliver_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_deliver_to', to='chore_app.Address')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_listed', to='chore_app.User')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_location', to='chore_app.Address')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_worked', to='chore_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_address', to='chore_app.User'),
        ),
    ]
