# Generated by Django 2.2 on 2021-04-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0003_auto_20210402_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='deliver_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_deliver_to', to='chore_app.Address'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='lister',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_listed', to='chore_app.User'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_location', to='chore_app.Address'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_worked', to='chore_app.User'),
        ),
    ]
