# Generated by Django 3.1.7 on 2021-04-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0004_auto_20210402_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('user_lvl', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('user_lvl', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chore',
            name='deliver_to',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='lister',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='location',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='worker',
        ),
        migrations.AlterField(
            model_name='chore',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='chore',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chore',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='chore',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_customer', to='chore_app.customer'),
        ),
        migrations.AddField(
            model_name='chore',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_driven', to='chore_app.driver'),
        ),
    ]
