# Generated by Django 3.1.7 on 2021-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0007_auto_20210405_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.CharField(max_length=5),
        ),
    ]
