# Generated by Django 2.2 on 2021-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0008_auto_20210405_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
