# Generated by Django 3.1.7 on 2021-04-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0010_auto_20210407_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_driven', to='chore_app.driver'),
        ),
    ]
